export interface PracticeProblem {
  id: string;
  title: string;
  difficulty: "Easy" | "Medium" | "Hard";
  estimatedTime: string;
  description: string;
  starterCode: string;
  exampleInput?: string;
  exampleOutput?: string;
}

export const BUILTIN_PROBLEMS: PracticeProblem[] = [
  {
    id: "hello-world",
    title: "Hello World",
    difficulty: "Easy",
    estimatedTime: "2 mins",
    description: "Write a program that prints 'Hello, World!' to the console.",
    starterCode: "# Write your solution below\nprint('Hello, World!')\n",
    exampleInput: "None",
    exampleOutput: "Hello, World!",
  },
  {
    id: "print-1-100",
    title: "Print Numbers 1-100",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Write a program that prints numbers from 1 to 100 on separate lines using a loop.",
    starterCode: "# Write a loop to print numbers from 1 to 100\nfor i in range(1, 101):\n    print(i)\n",
    exampleInput: "None",
    exampleOutput: "1\n2\n...\n100",
  },
  {
    id: "even-odd",
    title: "Even Odd Check",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read an integer input and print 'Even' if the number is divisible by 2, otherwise print 'Odd'.",
    starterCode: "n = int(input())\n# Write your if-else logic here\nif n % 2 == 0:\n    print('Even')\nelse:\n    print('Odd')\n",
    exampleInput: "7",
    exampleOutput: "Odd",
  },
  {
    id: "largest-number",
    title: "Largest of Three Numbers",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read three numbers from input (one per line) and print the largest among them.",
    starterCode: "a = int(input())\nb = int(input())\nc = int(input())\n\n# Print the maximum number\nprint(max(a, b, c))\n",
    exampleInput: "15\n42\n28",
    exampleOutput: "42",
  },
  {
    id: "palindrome",
    title: "Palindrome String",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Check if a given string input is a palindrome (reads the same forwards and backwards). Print 'Palindrome' or 'Not Palindrome'.",
    starterCode: "s = input().strip()\nif s == s[::-1]:\n    print('Palindrome')\nelse:\n    print('Not Palindrome')\n",
    exampleInput: "racecar",
    exampleOutput: "Palindrome",
  },
  {
    id: "prime-number",
    title: "Prime Number Checker",
    difficulty: "Medium",
    estimatedTime: "8 mins",
    description: "Read an integer n (>1) and print 'Prime' if n is a prime number, otherwise print 'Not Prime'.",
    starterCode: "n = int(input())\nis_prime = True\nif n <= 1:\n    is_prime = False\nelse:\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            is_prime = False\n            break\n\nprint('Prime' if is_prime else 'Not Prime')\n",
    exampleInput: "29",
    exampleOutput: "Prime",
  },
  {
    id: "factorial",
    title: "Factorial Calculation",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read a non-negative integer n and calculate its factorial (n!). Print the result.",
    starterCode: "import math\nn = int(input())\nprint(math.factorial(n))\n",
    exampleInput: "5",
    exampleOutput: "120",
  },
  {
    id: "fibonacci",
    title: "Fibonacci Series",
    difficulty: "Easy",
    estimatedTime: "7 mins",
    description: "Read an integer n and print the first n terms of the Fibonacci sequence separated by spaces.",
    starterCode: "n = int(input())\na, b = 0, 1\nfor _ in range(n):\n    print(a, end=' ')\n    a, b = b, a + b\nprint()\n",
    exampleInput: "6",
    exampleOutput: "0 1 1 2 3 5",
  },
  {
    id: "reverse-string",
    title: "Reverse String",
    difficulty: "Easy",
    estimatedTime: "3 mins",
    description: "Read a string from input and print its reverse.",
    starterCode: "text = input()\nprint(text[::-1])\n",
    exampleInput: "Classora",
    exampleOutput: "arossalC",
  },
  {
    id: "count-vowels",
    title: "Count Vowels",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Count and print the number of vowels (a, e, i, o, u case-insensitive) in a given string.",
    starterCode: "text = input().lower()\nvowels = set('aeiou')\ncount = sum(1 for char in text if char in vowels)\nprint(count)\n",
    exampleInput: "Education",
    exampleOutput: "5",
  },
  {
    id: "sum-of-digits",
    title: "Sum of Digits",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Calculate and print the sum of all digits of a given positive integer.",
    starterCode: "n = input().strip()\nprint(sum(int(digit) for digit in n if digit.isdigit()))\n",
    exampleInput: "9876",
    exampleOutput: "30",
  },
  {
    id: "armstrong-number",
    title: "Armstrong Number",
    difficulty: "Medium",
    estimatedTime: "8 mins",
    description: "An Armstrong number of n digits is equal to the sum of the nth powers of its digits. Check if an integer is an Armstrong number.",
    starterCode: "num_str = input().strip()\nnum = int(num_str)\npower = len(num_str)\ntotal = sum(int(d)**power for d in num_str)\nif total == num:\n    print('Armstrong Number')\nelse:\n    print('Not Armstrong')\n",
    exampleInput: "153",
    exampleOutput: "Armstrong Number",
  },
  {
    id: "pattern-printing",
    title: "Pattern Printing (Pyramid)",
    difficulty: "Easy",
    estimatedTime: "7 mins",
    description: "Read an integer n and print a right-angled triangle pattern of asterisks with n rows.",
    starterCode: "n = int(input())\nfor i in range(1, n + 1):\n    print('* ' * i)\n",
    exampleInput: "4",
    exampleOutput: "* \n* * \n* * * \n* * * * ",
  },
  {
    id: "binary-search",
    title: "Binary Search",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Binary Search. Read a target number from line 1, and space-separated sorted numbers from line 2. Print index or -1.",
    starterCode: "target = int(input())\narr = list(map(int, input().split()))\n\nleft, right = 0, len(arr) - 1\nfound = -1\nwhile left <= right:\n    mid = (left + right) // 2\n    if arr[mid] == target:\n        found = mid\n        break\n    elif arr[mid] < target:\n        left = mid + 1\n    else:\n        right = mid - 1\n\nprint(found)\n",
    exampleInput: "23\n10 15 23 45 70 89",
    exampleOutput: "2",
  },
  {
    id: "linear-search",
    title: "Linear Search",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Search for a target value in a list of numbers. Print the index if found, else -1.",
    starterCode: "target = int(input())\narr = list(map(int, input().split()))\n\ntry:\n    print(arr.index(target))\nexcept ValueError:\n    print(-1)\n",
    exampleInput: "42\n10 20 30 42 50",
    exampleOutput: "3",
  },
  {
    id: "bubble-sort",
    title: "Bubble Sort Algorithm",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Bubble Sort to sort a list of numbers in ascending order.",
    starterCode: "arr = list(map(int, input().split()))\nn = len(arr)\nfor i in range(n):\n    for j in range(0, n - i - 1):\n        if arr[j] > arr[j + 1]:\n            arr[j], arr[j + 1] = arr[j + 1], arr[j]\nprint(*arr)\n",
    exampleInput: "64 34 25 12 22 11 90",
    exampleOutput: "11 12 22 25 34 64 90",
  },
  {
    id: "selection-sort",
    title: "Selection Sort Algorithm",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Selection Sort to sort an array of numbers in ascending order.",
    starterCode: "arr = list(map(int, input().split()))\nfor i in range(len(arr)):\n    min_idx = i\n    for j in range(i + 1, len(arr)):\n        if arr[j] < arr[min_idx]:\n            min_idx = j\n    arr[i], arr[min_idx] = arr[min_idx], arr[i]\nprint(*arr)\n",
    exampleInput: "29 10 14 37 14",
    exampleOutput: "10 14 14 29 37",
  },
  {
    id: "insertion-sort",
    title: "Insertion Sort Algorithm",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Insertion Sort to sort an array in ascending order.",
    starterCode: "arr = list(map(int, input().split()))\nfor i in range(1, len(arr)):\n    key = arr[i]\n    j = i - 1\n    while j >= 0 and key < arr[j]:\n        arr[j + 1] = arr[j]\n        j -= 1\n    arr[j + 1] = key\nprint(*arr)\n",
    exampleInput: "12 11 13 5 6",
    exampleOutput: "5 6 11 12 13",
  },
  {
    id: "merge-sort",
    title: "Merge Sort Algorithm",
    difficulty: "Hard",
    estimatedTime: "15 mins",
    description: "Implement Divide-and-Conquer Merge Sort.",
    starterCode: "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n\narr = list(map(int, input().split()))\nprint(*merge_sort(arr))\n",
    exampleInput: "38 27 43 3 9 82 10",
    exampleOutput: "3 9 10 27 38 43 82",
  },
  {
    id: "quick-sort",
    title: "Quick Sort Algorithm",
    difficulty: "Hard",
    estimatedTime: "15 mins",
    description: "Implement Quick Sort using partition pivot logic.",
    starterCode: "def quick_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quick_sort(left) + middle + quick_sort(right)\n\narr = list(map(int, input().split()))\nprint(*quick_sort(arr))\n",
    exampleInput: "10 7 8 9 1 5",
    exampleOutput: "1 5 7 8 9 10",
  },
  {
    id: "stack-using-list",
    title: "Stack Data Structure using List",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Create a simple Stack class supporting push, pop, peek, and isEmpty operations.",
    starterCode: "class Stack:\n    def __init__(self):\n        self.items = []\n    def push(self, item):\n        self.items.append(item)\n    def pop(self):\n        return self.items.pop() if not self.is_empty() else 'Empty'\n    def peek(self):\n        return self.items[-1] if not self.is_empty() else 'Empty'\n    def is_empty(self):\n        return len(self.items) == 0\n\ns = Stack()\ns.push(10)\ns.push(20)\ns.push(30)\nprint('Popped:', s.pop())\nprint('Top:', s.peek())\n",
    exampleInput: "None",
    exampleOutput: "Popped: 30\nTop: 20",
  },
  {
    id: "queue-using-list",
    title: "Queue Data Structure using List",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Create a Queue class supporting enqueue and dequeue operations.",
    starterCode: "class Queue:\n    def __init__(self):\n        self.items = []\n    def enqueue(self, item):\n        self.items.append(item)\n    def dequeue(self):\n        return self.items.pop(0) if self.items else 'Empty'\n\nq = Queue()\nq.enqueue('Task A')\nq.enqueue('Task B')\nprint(q.dequeue())\nprint(q.dequeue())\n",
    exampleInput: "None",
    exampleOutput: "Task A\nTask B",
  },
  {
    id: "dictionary-practice",
    title: "Dictionary Word Frequency Counter",
    difficulty: "Easy",
    estimatedTime: "7 mins",
    description: "Read a sentence and print the frequency of each word as a dictionary.",
    starterCode: "sentence = input().split()\nfreq = {}\nfor word in sentence:\n    word = word.lower()\n    freq[word] = freq.get(word, 0) + 1\nprint(freq)\n",
    exampleInput: "apple banana apple orange banana apple",
    exampleOutput: "{'apple': 3, 'banana': 2, 'orange': 1}",
  },
  {
    id: "file-handling",
    title: "In-Memory File String Processing",
    difficulty: "Medium",
    estimatedTime: "8 mins",
    description: "Process multi-line string contents line by line using Python string methods.",
    starterCode: "data = '''Line 1: Python\\nLine 2: JavaScript\\nLine 3: C++'''\nlines = data.strip().split('\\n')\nfor index, line in enumerate(lines, start=1):\n    print(f'{index}. {line}')\n",
    exampleInput: "None",
    exampleOutput: "1. Line 1: Python\n2. Line 2: JavaScript\n3. Line 3: C++",
  },
  {
    id: "exception-handling",
    title: "Safe Division Exception Handling",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read two numbers and perform division. Handle ZeroDivisionError safely without crashing.",
    starterCode: "try:\n    a = float(input())\n    b = float(input())\n    result = a / b\n    print(f'Result: {result}')\nexcept ZeroDivisionError:\n    print('Error: Division by zero is not allowed.')\nexcept ValueError:\n    print('Error: Invalid numerical input.')\n",
    exampleInput: "10\n0",
    exampleOutput: "Error: Division by zero is not allowed.",
  },
  {
    id: "simple-calculator",
    title: "Simple CLI Calculator",
    difficulty: "Easy",
    estimatedTime: "6 mins",
    description: "Read num1, operator (+, -, *, /), and num2 on separate lines. Print the calculated result.",
    starterCode: "num1 = float(input())\nop = input().strip()\nnum2 = float(input())\n\nif op == '+':\n    print(num1 + num2)\nelif op == '-':\n    print(num1 - num2)\nelif op == '*':\n    print(num1 * num2)\nelif op == '/':\n    print(num1 / num2 if num2 != 0 else 'Error: Div by zero')\nelse:\n    print('Invalid operator')\n",
    exampleInput: "12\n*\n4",
    exampleOutput: "48.0",
  },
];
