export interface PracticeProblem {
  id: string;
  title: string;
  difficulty: "Easy" | "Medium" | "Hard";
  estimatedTime: string;
  description: string;
  starterCode: string;
  exampleInput?: string;
  exampleOutput?: string;
}

export const BUILTIN_PROBLEMS: PracticeProblem[] = [
  {
    id: "hello-world",
    title: "Hello World",
    difficulty: "Easy",
    estimatedTime: "2 mins",
    description: "Write a program that prints 'Hello, World!' to the console.",
    starterCode: "# Write your Python solution below\n\n",
    exampleInput: "None",
    exampleOutput: "Hello, World!",
  },
  {
    id: "print-1-100",
    title: "Print Numbers 1-100",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Write a program that prints numbers from 1 to 100 on separate lines using a loop.",
    starterCode: "# Write a loop to print numbers from 1 to 100 below\n\n",
    exampleInput: "None",
    exampleOutput: "1\n2\n...\n100",
  },
  {
    id: "even-odd",
    title: "Even Odd Check",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read an integer input and print 'Even' if the number is divisible by 2, otherwise print 'Odd'.",
    starterCode: "# Read integer input\nn = int(input())\n\n# Write your even/odd logic below\n\n",
    exampleInput: "7",
    exampleOutput: "Odd",
  },
  {
    id: "largest-number",
    title: "Largest of Three Numbers",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read three numbers from input (one per line) and print the largest among them.",
    starterCode: "a = int(input())\nb = int(input())\nc = int(input())\n\n# Print the largest number below\n\n",
    exampleInput: "15\n42\n28",
    exampleOutput: "42",
  },
  {
    id: "palindrome",
    title: "Palindrome String",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Check if a given string input is a palindrome (reads the same forwards and backwards). Print 'Palindrome' or 'Not Palindrome'.",
    starterCode: "s = input().strip()\n\n# Check if palindrome and print result below\n\n",
    exampleInput: "racecar",
    exampleOutput: "Palindrome",
  },
  {
    id: "prime-number",
    title: "Prime Number Checker",
    difficulty: "Medium",
    estimatedTime: "8 mins",
    description: "Read an integer n (>1) and print 'Prime' if n is a prime number, otherwise print 'Not Prime'.",
    starterCode: "n = int(input())\n\n# Check if n is prime and print 'Prime' or 'Not Prime' below\n\n",
    exampleInput: "29",
    exampleOutput: "Prime",
  },
  {
    id: "factorial",
    title: "Factorial Calculation",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read a non-negative integer n and calculate its factorial (n!). Print the result.",
    starterCode: "n = int(input())\n\n# Calculate and print factorial below\n\n",
    exampleInput: "5",
    exampleOutput: "120",
  },
  {
    id: "fibonacci",
    title: "Fibonacci Series",
    difficulty: "Easy",
    estimatedTime: "7 mins",
    description: "Read an integer n and print the first n terms of the Fibonacci sequence separated by spaces.",
    starterCode: "n = int(input())\n\n# Print the first n Fibonacci numbers separated by spaces below\n\n",
    exampleInput: "6",
    exampleOutput: "0 1 1 2 3 5",
  },
  {
    id: "reverse-string",
    title: "Reverse String",
    difficulty: "Easy",
    estimatedTime: "3 mins",
    description: "Read a string from input and print its reverse.",
    starterCode: "text = input()\n\n# Print the reverse of the string below\n\n",
    exampleInput: "Classora",
    exampleOutput: "arossalC",
  },
  {
    id: "count-vowels",
    title: "Count Vowels",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Count and print the number of vowels (a, e, i, o, u case-insensitive) in a given string.",
    starterCode: "text = input()\n\n# Count and print the number of vowels below\n\n",
    exampleInput: "Education",
    exampleOutput: "5",
  },
  {
    id: "sum-of-digits",
    title: "Sum of Digits",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Calculate and print the sum of all digits of a given positive integer.",
    starterCode: "n = input().strip()\n\n# Calculate and print the sum of digits below\n\n",
    exampleInput: "9876",
    exampleOutput: "30",
  },
  {
    id: "armstrong-number",
    title: "Armstrong Number",
    difficulty: "Medium",
    estimatedTime: "8 mins",
    description: "An Armstrong number of n digits is equal to the sum of the nth powers of its digits. Check if an integer is an Armstrong number.",
    starterCode: "num_str = input().strip()\n\n# Check if Armstrong number and print result below\n\n",
    exampleInput: "153",
    exampleOutput: "Armstrong Number",
  },
  {
    id: "pattern-printing",
    title: "Pattern Printing (Pyramid)",
    difficulty: "Easy",
    estimatedTime: "7 mins",
    description: "Read an integer n and print a right-angled triangle pattern of asterisks with n rows.",
    starterCode: "n = int(input())\n\n# Print asterisk pyramid pattern below\n\n",
    exampleInput: "4",
    exampleOutput: "* \n* * \n* * * \n* * * * ",
  },
  {
    id: "binary-search",
    title: "Binary Search",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Binary Search. Read a target number from line 1, and space-separated sorted numbers from line 2. Print index or -1.",
    starterCode: "target = int(input())\narr = list(map(int, input().split()))\n\n# Write Binary Search algorithm below\n\n",
    exampleInput: "23\n10 15 23 45 70 89",
    exampleOutput: "2",
  },
  {
    id: "linear-search",
    title: "Linear Search",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Search for a target value in a list of numbers. Print the index if found, else -1.",
    starterCode: "target = int(input())\narr = list(map(int, input().split()))\n\n# Write Linear Search below\n\n",
    exampleInput: "42\n10 20 30 42 50",
    exampleOutput: "3",
  },
  {
    id: "bubble-sort",
    title: "Bubble Sort Algorithm",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Bubble Sort to sort a list of numbers in ascending order.",
    starterCode: "arr = list(map(int, input().split()))\n\n# Write Bubble Sort algorithm below\n\n",
    exampleInput: "64 34 25 12 22 11 90",
    exampleOutput: "11 12 22 25 34 64 90",
  },
  {
    id: "selection-sort",
    title: "Selection Sort Algorithm",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Selection Sort to sort an array of numbers in ascending order.",
    starterCode: "arr = list(map(int, input().split()))\n\n# Write Selection Sort algorithm below\n\n",
    exampleInput: "29 10 14 37 14",
    exampleOutput: "10 14 14 29 37",
  },
  {
    id: "insertion-sort",
    title: "Insertion Sort Algorithm",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Implement Insertion Sort to sort an array in ascending order.",
    starterCode: "arr = list(map(int, input().split()))\n\n# Write Insertion Sort algorithm below\n\n",
    exampleInput: "12 11 13 5 6",
    exampleOutput: "5 6 11 12 13",
  },
  {
    id: "merge-sort",
    title: "Merge Sort Algorithm",
    difficulty: "Hard",
    estimatedTime: "15 mins",
    description: "Implement Divide-and-Conquer Merge Sort.",
    starterCode: "arr = list(map(int, input().split()))\n\n# Write Merge Sort algorithm below\n\n",
    exampleInput: "38 27 43 3 9 82 10",
    exampleOutput: "3 9 10 27 38 43 82",
  },
  {
    id: "quick-sort",
    title: "Quick Sort Algorithm",
    difficulty: "Hard",
    estimatedTime: "15 mins",
    description: "Implement Quick Sort using partition pivot logic.",
    starterCode: "arr = list(map(int, input().split()))\n\n# Write Quick Sort algorithm below\n\n",
    exampleInput: "10 7 8 9 1 5",
    exampleOutput: "1 5 7 8 9 10",
  },
  {
    id: "stack-using-list",
    title: "Stack Data Structure using List",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Create a simple Stack class supporting push, pop, peek, and isEmpty operations.",
    starterCode: "class Stack:\n    def __init__(self):\n        self.items = []\n    # Implement push, pop, peek, is_empty methods below\n\n",
    exampleInput: "None",
    exampleOutput: "Popped: 30\nTop: 20",
  },
  {
    id: "queue-using-list",
    title: "Queue Data Structure using List",
    difficulty: "Medium",
    estimatedTime: "10 mins",
    description: "Create a Queue class supporting enqueue and dequeue operations.",
    starterCode: "class Queue:\n    def __init__(self):\n        self.items = []\n    # Implement enqueue and dequeue methods below\n\n",
    exampleInput: "None",
    exampleOutput: "Task A\nTask B",
  },
  {
    id: "dictionary-practice",
    title: "Dictionary Word Frequency Counter",
    difficulty: "Easy",
    estimatedTime: "7 mins",
    description: "Read a sentence and print the frequency of each word as a dictionary.",
    starterCode: "sentence = input().split()\n\n# Count word frequencies using a dictionary below\n\n",
    exampleInput: "apple banana apple orange banana apple",
    exampleOutput: "{'apple': 3, 'banana': 2, 'orange': 1}",
  },
  {
    id: "file-handling",
    title: "In-Memory File String Processing",
    difficulty: "Medium",
    estimatedTime: "8 mins",
    description: "Process multi-line string contents line by line using Python string methods.",
    starterCode: "data = '''Line 1: Python\\nLine 2: JavaScript\\nLine 3: C++'''\n\n# Process lines line by line below\n\n",
    exampleInput: "None",
    exampleOutput: "1. Line 1: Python\n2. Line 2: JavaScript\n3. Line 3: C++",
  },
  {
    id: "exception-handling",
    title: "Safe Division Exception Handling",
    difficulty: "Easy",
    estimatedTime: "5 mins",
    description: "Read two numbers and perform division. Handle ZeroDivisionError safely without crashing.",
    starterCode: "# Read inputs\na = input()\nb = input()\n\n# Perform safe division using try-except below\n\n",
    exampleInput: "10\n0",
    exampleOutput: "Error: Division by zero is not allowed.",
  },
  {
    id: "simple-calculator",
    title: "Simple CLI Calculator",
    difficulty: "Easy",
    estimatedTime: "6 mins",
    description: "Read num1, operator (+, -, *, /), and num2 on separate lines. Print the calculated result.",
    starterCode: "num1 = float(input())\nop = input().strip()\nnum2 = float(input())\n\n# Calculate and print result based on operator below\n\n",
    exampleInput: "12\n*\n4",
    exampleOutput: "48.0",
  },
];
